"""Initial revision

Revision ID: 80ee28cabfd6
Revises: 
Create Date: 2025-11-29 20:29:57.203591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ee28cabfd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('honesty_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honesty_categories_is_adult'), 'honesty_categories', ['is_adult'], unique=False)
    op.create_index(op.f('ix_honesty_categories_is_premium'), 'honesty_categories', ['is_premium'], unique=False)
    op.create_index(op.f('ix_honesty_categories_is_visible'), 'honesty_categories', ['is_visible'], unique=False)
    op.create_index(op.f('ix_honesty_categories_order'), 'honesty_categories', ['order'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('honesty_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['honesty_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honesty_questions_category_id'), 'honesty_questions', ['category_id'], unique=False)
    op.create_index(op.f('ix_honesty_questions_order'), 'honesty_questions', ['order'], unique=False)
    op.create_table('premiums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premiums')
    op.drop_index(op.f('ix_honesty_questions_order'), table_name='honesty_questions')
    op.drop_index(op.f('ix_honesty_questions_category_id'), table_name='honesty_questions')
    op.drop_table('honesty_questions')
    op.drop_table('users')
    op.drop_index(op.f('ix_honesty_categories_order'), table_name='honesty_categories')
    op.drop_index(op.f('ix_honesty_categories_is_visible'), table_name='honesty_categories')
    op.drop_index(op.f('ix_honesty_categories_is_premium'), table_name='honesty_categories')
    op.drop_index(op.f('ix_honesty_categories_is_adult'), table_name='honesty_categories')
    op.drop_table('honesty_categories')
    op.drop_table('admins')
    # ### end Alembic commands ###
